// <auto-generated />
namespace ProductStore.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddHashInsteadPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHashInsteadPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201809251716122_AddHashInsteadPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
